baseURL = 'https://joemay96.github.io/swh-blog/'
languageCode = 'de-de'
title = 'Josef SWH Blog'
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
author = "Josef Mayer"
description = "Yeah you git me!"
github = "@joemay96"
# facebook = "MeiK2333"
# twitter = "MeiK2333"
linkedin = "https://www.linkedin.com/in/josef-mayer-91491a21b/"
# instagram = "MeiK2333"
# tumblr = "MeiK2333"
email = "me@josefmayer.me"
url = "https://sharky.live"
keywords = "sketching with hardware, swh, blog, uni"
rss = true
lastmod = true
userStatusEmoji = "🧘"
favicon = "/images/favicon.png"
image = "/images/profile.jpeg"
location = "Germany"
enableGitalk = false

# [params.gitalk]
# clientID = "Your client ID"
# clientSecret = "Your client secret"
# repo = "repo"
# owner = "MeiK2333"
# admin = "MeiK2333"
# id = "location.pathname"
# labels = "gitalk"
# perPage = 15
# pagerDirection = "last"
# createIssueManually = true
# distractionFreeMode = false


#! Links die man einstellen kann
# [[params.links]]
# title = "Link"
# href = "https://github.com/joemay96"
[[params.links]]
title = "Website"
href = "https://sharky.live"
icon = "./images/web.png"

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]
